/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IAuthResponse {
    access_token?: string;
    refresh_token?: string;
}


export class AuthResponse  implements IAuthResponse  {
    access_token: string;
    refresh_token: string;
}

