/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IInstitutionSubscriptionDto {
    id?: number;
    isActive?: boolean;
    createdAt?: Date;
    modifiedAt?: Date;
    institutionId?: number;
}


export class InstitutionSubscriptionDto  implements IInstitutionSubscriptionDto  {
    id: number;
    isActive: boolean;
    createdAt: Date;
    modifiedAt: Date;
    institutionId: number;
}

