/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IInstitutionDto {
    id?: number;
    name?: string;
    fullAddress?: string;
    email?: string;
    phoneNr?: string;
    createdAt?: Date;
    modifiedAt?: Date;
}


export class InstitutionDto  implements IInstitutionDto  {
    id: number;
    name: string;
    fullAddress: string;
    email: string;
    phoneNr: string;
    createdAt: Date;
    modifiedAt: Date;
}

