/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface ILoginMessage {
    message?: string;
}


export class LoginMessage  implements ILoginMessage  {
    message: string;
}

