/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUpsertUserDto {
    walletAddress?: string;
    name?: string;
    email?: string;
    role?: number;
    lockEnabled?: boolean;
}


export class UpsertUserDto  implements IUpsertUserDto  {
    walletAddress: string;
    name: string;
    email: string;
    role: number;
    lockEnabled: boolean;
}

