/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUpsertInstitutionDto {
    name?: string;
    fullAddress?: string;
    email?: string;
    phoneNr?: string;
}


export class UpsertInstitutionDto  implements IUpsertInstitutionDto  {
    name: string;
    fullAddress: string;
    email: string;
    phoneNr: string;
}

