/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUpsertInstitutionManagerDto {
    name?: string;
    email?: string;
    walletAddress?: string;
}


export class UpsertInstitutionManagerDto  implements IUpsertInstitutionManagerDto  {
    name: string;
    email: string;
    walletAddress: string;
}

