/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUserDto {
    id?: number;
    walletAddress?: string;
    name?: string;
    email?: string;
    createdAt?: Date;
    modifiedAt?: Date;
    role?: number;
    lockEnabled?: boolean;
    loginAttempts?: number;
    lockedUntil?: Date;
    refreshToken?: string;
}


export class UserDto  implements IUserDto  {
    id: number;
    walletAddress: string;
    name: string;
    email: string;
    createdAt: Date;
    modifiedAt: Date;
    role: number;
    lockEnabled: boolean;
    loginAttempts: number;
    lockedUntil: Date;
    refreshToken: string;
}

