/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUserListDto {
    id?: number;
    walletAddress?: string;
    name?: string;
    email?: string;
}


export class UserListDto  implements IUserListDto  {
    id: number;
    walletAddress: string;
    name: string;
    email: string;
}

