/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IInstitutionListDto {
    id?: number;
    name?: string;
}


export class InstitutionListDto  implements IInstitutionListDto  {
    id: number;
    name: string;
}

