/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IInstitutionManagerDto {
    id?: number;
    walletAddress?: string;
    name?: string;
    email?: string;
    createdAt?: Date;
    modifiedAt?: Date;
    institutionId?: number;
}


export class InstitutionManagerDto  implements IInstitutionManagerDto  {
    id: number;
    walletAddress: string;
    name: string;
    email: string;
    createdAt: Date;
    modifiedAt: Date;
    institutionId: number;
}

