/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface ILoginDto {
    address?: string;
    signature?: string;
}


export class LoginDto  implements ILoginDto  {
    address: string;
    signature: string;
}

