/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */



export interface IUpdateUserDto {
    id?: number;
    address?: string;
    name?: string;
    email?: string;
    createdAt?: Date;
    modifiedAt?: Date;
    role?: number;
    lockEnabled?: boolean;
    loginAttempts?: number;
    lockedUntil?: Date;
}


export class UpdateUserDto  implements IUpdateUserDto  {
    id: number;
    address: string;
    name: string;
    email: string;
    createdAt: Date;
    modifiedAt: Date;
    role: number;
    lockEnabled: boolean;
    loginAttempts: number;
    lockedUntil: Date;
}

