version: "3.9"
name: doctive-local
services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=D0ct1v3_1337
    ports: 
      - 1433:1433

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports: 
      - 27017:27017

  redis: 
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - 6379:6379

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../storage/minio:/data
    command: server /data  --console-address ":9001"
